/**
 * MS-PPTX 25.0 (2024-08-20) extension conformance profile.
 *
 * Tracker only: records namespace, package, Markup Compatibility wrapper, API,
 * semantic contract, and Office fixture for each supported or planned extension.
 * Child issues #87–#93 implement features. Do not add emitters here.
 *
 * @see standards/ms-pptx/CONFORMANCE-PROFILE.md
 * @see [MS-PPTX] §1.5 Applicability Statement, §2 Extensions
 */

export const MS_PPTX_VERSION = '25.0' as const
export const MS_PPTX_DATE = '2024-08-20' as const

/** [MS-PPTX] §2: one of these MUST wrap every extension. */
export type MarkupCompatibilityWrapper = 'mc:Ignorable' | 'mc:AlternateContent' | 'extLst'

export type ExtensionStatus = 'supported' | 'partial' | 'planned'

export type TargetMode = 'Internal' | 'External' | 'Internal|External'

export interface MsPptxExtension {
	/** Stable catalog id (kebab-case). */
	id: string
	title: string
	/** Spec section, e.g. `§2.2.15`. */
	spec: string
	/** Child tracker issue, or null when the surface is already shipped / unassigned. */
	issue: number | null
	status: ExtensionStatus
	namespace: string
	/** Conventional Office prefix (p14, p15, p188, …). */
	prefix: string
	/** Host element / part the extension hangs off. */
	host: string
	/** Package part path pattern, or the host part when the extension is inline. */
	part: string
	contentType: string | null
	relationship: string | null
	targetMode: TargetMode | null
	wrapper: MarkupCompatibilityWrapper
	/** `p:ext/@uri` when wrapper is extLst. */
	extUri: string | null
	/** `mc:Choice/@Requires` prefix when wrapper is AlternateContent. */
	choiceRequires: string | null
	/** Mandated Fallback child when wrapper is AlternateContent. */
	fallback: string | null
	/** Public API that emits or will emit this extension. */
	api: string
	/** Semantic package contract (cardinality, rels, root). */
	packageContract: string
	/** Office / semantic fixture that proves the contract. */
	officeFixture: string
	/** Appendix A schema file under `standards/ms-pptx/sections/`. */
	schema: string
}

export const MS_PPTX_NAMESPACES = {
	mc: 'http://schemas.openxmlformats.org/markup-compatibility/2006',
	p: 'http://schemas.openxmlformats.org/presentationml/2006/main',
	a: 'http://schemas.openxmlformats.org/drawingml/2006/main',
	r: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships',
	a14: 'http://schemas.microsoft.com/office/drawing/2010/main',
	m: 'http://schemas.openxmlformats.org/officeDocument/2006/math',
	p14: 'http://schemas.microsoft.com/office/powerpoint/2010/main',
	p15: 'http://schemas.microsoft.com/office/powerpoint/2012/main',
	pc: 'http://schemas.microsoft.com/office/powerpoint/2013/main/command',
	p159: 'http://schemas.microsoft.com/office/powerpoint/2015/09/main',
	p1510: 'http://schemas.microsoft.com/office/powerpoint/2015/10/main',
	p15m: 'http://schemas.microsoft.com/office/powerpoint/2015/main',
	p16: 'http://schemas.microsoft.com/office/powerpoint/2016/main',
	p166: 'http://schemas.microsoft.com/office/powerpoint/2016/6/main',
	p16sz: 'http://schemas.microsoft.com/office/powerpoint/2016/sectionzoom',
	p16slz: 'http://schemas.microsoft.com/office/powerpoint/2016/slidezoom',
	p16smz: 'http://schemas.microsoft.com/office/powerpoint/2016/summaryzoom',
	p173: 'http://schemas.microsoft.com/office/powerpoint/2017/3/main',
	p1710: 'http://schemas.microsoft.com/office/powerpoint/2017/10/main',
	p184: 'http://schemas.microsoft.com/office/powerpoint/2018/4/main',
	p188: 'http://schemas.microsoft.com/office/powerpoint/2018/8/main',
	p199c: 'http://schemas.microsoft.com/office/powerpoint/2019/9/main/command',
	p2020: 'http://schemas.microsoft.com/office/powerpoint/2020/02/main',
	p2203: 'http://schemas.microsoft.com/office/powerpoint/2022/03/main',
	p2206c: 'http://schemas.microsoft.com/office/powerpoint/2022/06/main/command',
	p2208: 'http://schemas.microsoft.com/office/powerpoint/2022/08/main',
	p2302: 'http://schemas.microsoft.com/office/powerpoint/2023/02/main',
	we: 'http://schemas.microsoft.com/office/webextensions/webextension/2010/11',
	p13app: 'http://schemas.microsoft.com/office/powerpoint/2013/contentapp',
	inkAction: 'http://schemas.microsoft.com/office/powerpoint/2014/inkAction',
} as const

export const MS_PPTX_SCHEMAS = [
	{ appendix: '5.1', namespace: MS_PPTX_NAMESPACES.p14, file: '150_http-schemas-microsoft-com-office-powerpoint-2010-main-schema.md' },
	{ appendix: '5.2', namespace: MS_PPTX_NAMESPACES.p15, file: '151_http-schemas-microsoft-com-office-powerpoint-2012-main-schema.md' },
	{ appendix: '5.3', namespace: MS_PPTX_NAMESPACES.pc, file: '152_http-schemas-microsoft-com-office-powerpoint-2013-main-command-schema.md' },
	{ appendix: '5.4', namespace: MS_PPTX_NAMESPACES.p159, file: '153_http-schemas-microsoft-com-office-powerpoint-2015-09-main-schema.md' },
	{ appendix: '5.5', namespace: MS_PPTX_NAMESPACES.p1510, file: '154_http-schemas-microsoft-com-office-powerpoint-2015-10-main-schema.md' },
	{ appendix: '5.6', namespace: MS_PPTX_NAMESPACES.p15m, file: '155_http-schemas-microsoft-com-office-powerpoint-2015-main-schema.md' },
	{ appendix: '5.7', namespace: MS_PPTX_NAMESPACES.p166, file: '156_http-schemas-microsoft-com-office-powerpoint-2016-6-main-schema.md' },
	{ appendix: '5.8', namespace: MS_PPTX_NAMESPACES.p16sz, file: '157_http-schemas-microsoft-com-office-powerpoint-2016-sectionzoom-schema.md' },
	{ appendix: '5.9', namespace: MS_PPTX_NAMESPACES.p16slz, file: '158_http-schemas-microsoft-com-office-powerpoint-2016-slidezoom-schema.md' },
	{ appendix: '5.10', namespace: MS_PPTX_NAMESPACES.p16smz, file: '159_http-schemas-microsoft-com-office-powerpoint-2016-summaryzoom-schema.md' },
	{ appendix: '5.11', namespace: MS_PPTX_NAMESPACES.p1710, file: '160_http-schemas-microsoft-com-office-powerpoint-2017-10-main-schema.md' },
	{ appendix: '5.12', namespace: MS_PPTX_NAMESPACES.p173, file: '161_http-schemas-microsoft-com-office-powerpoint-2017-3-main-schema.md' },
	{ appendix: '5.13', namespace: MS_PPTX_NAMESPACES.p184, file: '162_http-schemas-microsoft-com-office-powerpoint-2018-4-main-schema.md' },
	{ appendix: '5.14', namespace: MS_PPTX_NAMESPACES.p188, file: '163_http-schemas-microsoft-com-office-powerpoint-2018-8-main-schema.md' },
	{ appendix: '5.15', namespace: MS_PPTX_NAMESPACES.p199c, file: '164_http-schemas-microsoft-com-office-powerpoint-2019-9-main-command-schema.md' },
	{ appendix: '5.16', namespace: MS_PPTX_NAMESPACES.p2020, file: '165_http-schemas-microsoft-com-office-powerpoint-2020-02-main-schema.md' },
	{ appendix: '5.17', namespace: MS_PPTX_NAMESPACES.p2203, file: '166_http-schemas-microsoft-com-office-powerpoint-2022-03-main-schema.md' },
	{ appendix: '5.18', namespace: MS_PPTX_NAMESPACES.p2206c, file: '167_http-schemas-microsoft-com-office-powerpoint-2022-06-main-command-schema.md' },
	{ appendix: '5.19', namespace: MS_PPTX_NAMESPACES.p2208, file: '168_http-schemas-microsoft-com-office-powerpoint-2022-08-main-schema.md' },
	{ appendix: '5.20', namespace: MS_PPTX_NAMESPACES.p2302, file: '169_http-schemas-microsoft-com-office-powerpoint-2023-02-main-schema.md' },
] as const

const EXT: MsPptxExtension[] = [
	{
		id: 'transition-modern',
		title: 'Slide transition extensions',
		spec: '§2.2.1',
		issue: 82,
		status: 'supported',
		namespace: MS_PPTX_NAMESPACES.p14,
		prefix: 'p14|p15|p16',
		host: 'p:sld / p:sldLayout / p:sldMaster',
		part: 'ppt/slides/slideN.xml',
		contentType: 'application/vnd.openxmlformats-officedocument.presentationml.slide+xml',
		relationship: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide',
		targetMode: 'Internal',
		wrapper: 'mc:AlternateContent',
		extUri: null,
		choiceRequires: 'p14|p15|p16',
		fallback: 'p:transition (ECMA-376 base type)',
		api: 'slide.addTransition({ type, duration, … })',
		packageContract: 'Modern types (vortex…morph) MUST use mc:AlternateContent with a base Fallback; p14:dur is optional. Slide root SHOULD list p14 on mc:Ignorable when duration is present.',
		officeFixture: 'test/issues.test.ts #transition:* (semantic). Office: open morph + fade deck, confirm transition gallery + duration survive save.',
		schema: '150_…2010-main-schema.md; morph uses 2016/main (not a separate Appendix A file)',
	},
	{
		id: 'animation-timing',
		title: 'Animation info extensions',
		spec: '§2.2.2',
		issue: 82,
		status: 'partial',
		namespace: MS_PPTX_NAMESPACES.p14,
		prefix: 'p14',
		host: 'p:sld / p:timing',
		part: 'ppt/slides/slideN.xml',
		contentType: 'application/vnd.openxmlformats-officedocument.presentationml.slide+xml',
		relationship: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide',
		targetMode: 'Internal',
		wrapper: 'mc:AlternateContent',
		extUri: null,
		choiceRequires: 'p14',
		fallback: 'p:timing (ECMA-376)',
		api: 'slide.add* animation options (existing timing tree)',
		packageContract: 'Choice timing MAY add p14:bmkTgt and bounceEnd. Current emitters write ECMA-376 p:timing; bounceEnd / bmkTgt are not yet a public API.',
		officeFixture: 'Existing animation e2e. Office: planned bounceEnd/bmkTgt fixture when #83 completes media timing.',
		schema: '150_…2010-main-schema.md',
	},
	{
		id: 'content-part',
		title: 'Content part extensions',
		spec: '§2.2.3',
		issue: 87,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p14,
		prefix: 'p14',
		host: 'p:grpSp / p:spTree',
		part: 'ppt/slides/slideN.xml + related content part',
		contentType: '(content-part specific; ISO/IEC 29500 CT_Rel target)',
		relationship: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/image (or content-part rel)',
		targetMode: 'Internal',
		wrapper: 'mc:AlternateContent',
		extUri: null,
		choiceRequires: 'p14',
		fallback: 'p:sp',
		api: 'planned: slide.addContentPart(…)',
		packageContract: 'Choice MUST be p14:contentPart (nvContentPartPr + xfrm + extLst + bwMode). Fallback MUST be p:sp. Package rels MUST resolve.',
		officeFixture: 'planned test/fixtures/ms-pptx/content-part.roundtrip.pptx — Office open/save keeps contentPart Choice and sp Fallback.',
		schema: '150_…2010-main-schema.md',
	},
	{
		id: 'ink',
		title: 'Ink extensions',
		spec: '§2.2.3.1',
		issue: 87,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.inkAction,
		prefix: 'p14 + inkAction',
		host: 'p:spTree / p:grpSp',
		part: 'ppt/slides/slideN.xml + ink content part',
		contentType: '(ink / content-part)',
		relationship: '(content-part / ink)',
		targetMode: 'Internal',
		wrapper: 'mc:AlternateContent',
		choiceRequires: 'p14',
		extUri: null,
		fallback: 'p:pic',
		api: 'planned: slide.addInk(…) with pic fallback',
		packageContract: 'Choice Requires p14 (and inkAction). Fallback MUST be p:pic. Do not emit ink without a raster fallback.',
		officeFixture: 'planned test/fixtures/ms-pptx/ink.roundtrip.pptx — Office shows ink; down-level shows picture.',
		schema: '150_…2010-main-schema.md + [MS-ODRAWXML] inkAction',
	},
	{
		id: 'media-part',
		title: 'Media part',
		spec: '§2.1.1',
		issue: null,
		status: 'supported',
		namespace: MS_PPTX_NAMESPACES.p14,
		prefix: 'p14',
		host: 'slide / layout / master',
		part: 'ppt/media/*',
		contentType: 'ISO/IEC 29500 §15.2.2 / §15.2.17 audio or video type',
		relationship: 'http://schemas.microsoft.com/office/2007/relationships/media',
		targetMode: 'Internal|External',
		wrapper: 'extLst',
		extUri: '{DAA4B4D4-6D71-4841-9C94-3DE7FCFB9230}',
		choiceRequires: null,
		fallback: null,
		api: 'slide.addMedia({ type, path|data, … })',
		packageContract: 'Media part MUST be an explicit rel from Slide, Slide Layout, or Slide Master. MUST NOT have further rels. TargetMode Internal or External.',
		officeFixture: 'test/issues.test.ts #gap6 + test/coverage-objects.test.ts media. Office: play embedded audio/video after open/save.',
		schema: '150_…2010-main-schema.md',
	},
	{
		id: 'media-p14',
		title: 'Media trim / fade / bookmarks',
		spec: '§2.2.4',
		issue: null,
		status: 'supported',
		namespace: MS_PPTX_NAMESPACES.p14,
		prefix: 'p14',
		host: 'p:nvPr/p:extLst',
		part: 'ppt/slides/slideN.xml',
		contentType: null,
		relationship: 'http://schemas.microsoft.com/office/2007/relationships/media',
		targetMode: 'Internal|External',
		wrapper: 'extLst',
		extUri: '{DAA4B4D4-6D71-4841-9C94-3DE7FCFB9230}',
		choiceRequires: null,
		fallback: null,
		api: 'addMedia({ trim, fade, bookmarks })',
		packageContract: 'p14:media children trim / fade / bmkLst. r:embed MUST point at the media rel. Down-level readers ignore the ext.',
		officeFixture: 'test/issues.test.ts #gap6. Office: trim/fade/bookmark markers survive save.',
		schema: '150_…2010-main-schema.md',
	},
	{
		id: 'media-show-controls',
		title: 'Show media controls',
		spec: '§2.2.4',
		issue: null,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p14,
		prefix: 'p14',
		host: 'p:showPr/p:extLst',
		part: 'ppt/presProps.xml',
		contentType: 'application/vnd.openxmlformats-officedocument.presentationml.presProps+xml',
		relationship: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/presProps',
		targetMode: 'Internal',
		wrapper: 'extLst',
		extUri: '{2FDB2607-1784-4EEB-B798-7EB5836EED8A}',
		choiceRequires: null,
		fallback: null,
		api: 'planned: pptx.showMediaCtrls',
		packageContract: 'Zero-or-one p14:showMediaCtrls under presentationPr showPr extLst. Opt-in; unset MUST NOT change current presProps.',
		officeFixture: 'planned test/fixtures/ms-pptx/show-media-ctrls.roundtrip.pptx',
		schema: '150_…2010-main-schema.md',
	},
	{
		id: 'media-tracks',
		title: 'Media tracks (WebVTT) + tracksInfo',
		spec: '§2.1.3 / §2.2.4',
		issue: null,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p14,
		prefix: 'p14',
		host: 'p14:media/p:extLst',
		part: 'ppt/media/*.vtt',
		contentType: 'text/vtt',
		relationship: 'http://schemas.microsoft.com/office/2017/04/relationships/track',
		targetMode: 'Internal|External',
		wrapper: 'extLst',
		extUri: '{3AFAAA56-56D3-431D-BCD4-E75A35582382}',
		choiceRequires: null,
		fallback: null,
		api: 'planned: addMedia({ tracks })',
		packageContract: 'Track part is an explicit rel from Slide / Layout / Master. MUST NOT have further rels. tracksInfo ext on p14:media.',
		officeFixture: 'planned test/fixtures/ms-pptx/media-tracks.roundtrip.pptx — captions play in Office.',
		schema: '150_…2010-main-schema.md',
	},
	{
		id: 'narration',
		title: 'Narration flag',
		spec: '§2.2.14',
		issue: null,
		status: 'supported',
		namespace: MS_PPTX_NAMESPACES.p15,
		prefix: 'p15',
		host: 'p:nvPr/p:extLst',
		part: 'ppt/slides/slideN.xml',
		contentType: null,
		relationship: null,
		targetMode: null,
		wrapper: 'extLst',
		extUri: '{42D2F446-02D8-4167-A562-619A0277C38B}',
		choiceRequires: null,
		fallback: null,
		api: 'addMedia({ isNarration: true })',
		packageContract: 'p15:isNarration val="1" on the media nvPr extLst. Opt-in.',
		officeFixture: 'test/issues.test.ts #gap6. Office: media marked as narration after save.',
		schema: '151_…2012-main-schema.md',
	},
	{
		id: 'sections',
		title: 'Presentation sections',
		spec: '§2.2.5',
		issue: 88,
		status: 'supported',
		namespace: MS_PPTX_NAMESPACES.p14,
		prefix: 'p14',
		host: 'p:presentation/p:extLst',
		part: 'ppt/presentation.xml',
		contentType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml',
		relationship: null,
		targetMode: null,
		wrapper: 'extLst',
		extUri: '{521415D9-36F7-43E2-AB2F-B90AF26B5E84}',
		choiceRequires: null,
		fallback: null,
		api: 'pptx.addSection({ title })',
		packageContract: 'p14:sectionLst; each section has a stable GUID id and p14:sldIdLst of ST_SlideId values (not r:id). Zoom objects MUST reuse that GUID.',
		officeFixture: 'test/issues.test.ts zoom/section GUID check. Office: section pane + section zoom survive save.',
		schema: '150_…2010-main-schema.md',
	},
	{
		id: 'slideshow-browse',
		title: 'Slide-show browse mode',
		spec: '§2.2.6',
		issue: 89,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p14,
		prefix: 'p14',
		host: 'p:showPr/p:extLst',
		part: 'ppt/presProps.xml',
		contentType: 'application/vnd.openxmlformats-officedocument.presentationml.presProps+xml',
		relationship: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/presProps',
		targetMode: 'Internal',
		wrapper: 'extLst',
		extUri: '{F99C55AA-B7CB-42B0-86F8-08522FDF87E8}',
		choiceRequires: null,
		fallback: null,
		api: 'planned: pptx.browseMode',
		packageContract: 'Opt-in p14:browseMode on showPr. Unset MUST NOT emit the ext.',
		officeFixture: 'planned test/fixtures/ms-pptx/browse-mode.roundtrip.pptx',
		schema: '150_…2010-main-schema.md',
	},
	{
		id: 'slideshow-laser-color',
		title: 'Slide-show laser color',
		spec: '§2.2.6',
		issue: 89,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p14,
		prefix: 'p14',
		host: 'p:showPr/p:extLst',
		part: 'ppt/presProps.xml',
		contentType: 'application/vnd.openxmlformats-officedocument.presentationml.presProps+xml',
		relationship: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/presProps',
		targetMode: 'Internal',
		wrapper: 'extLst',
		extUri: '{EC167BDD-8182-4AB7-AECC-EB403E3ABB37}',
		choiceRequires: null,
		fallback: null,
		api: 'planned: pptx.laserColor',
		packageContract: 'p14:laserClr is a:CT_Color. Opt-in.',
		officeFixture: 'planned test/fixtures/ms-pptx/laser-color.roundtrip.pptx',
		schema: '150_…2010-main-schema.md',
	},
	{
		id: 'slideshow-laser-trace',
		title: 'Slide-show laser trace list',
		spec: '§2.2.6',
		issue: 89,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p14,
		prefix: 'p14',
		host: 'p:sld/p:extLst',
		part: 'ppt/slides/slideN.xml',
		contentType: 'application/vnd.openxmlformats-officedocument.presentationml.slide+xml',
		relationship: null,
		targetMode: null,
		wrapper: 'extLst',
		extUri: '{3A86A75C-4F4B-4683-9AE1-C65F6400EC91}',
		choiceRequires: null,
		fallback: null,
		api: 'planned: slide.laserTrace (generation typically omits recorded traces)',
		packageContract: 'p14:laserTraceLst on sld extLst. Opt-in; generators MAY skip recorded traces.',
		officeFixture: 'planned test/fixtures/ms-pptx/laser-trace.roundtrip.pptx (preserve-on-round-trip, not generate-by-default).',
		schema: '150_…2010-main-schema.md',
	},
	{
		id: 'slideshow-events',
		title: 'Slide-show event list',
		spec: '§2.2.6',
		issue: 89,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p14,
		prefix: 'p14',
		host: 'p:sld/p:extLst',
		part: 'ppt/slides/slideN.xml',
		contentType: 'application/vnd.openxmlformats-officedocument.presentationml.slide+xml',
		relationship: null,
		targetMode: null,
		wrapper: 'extLst',
		extUri: '{E180D4A7-C9FB-4DFB-919C-405C955672EB}',
		choiceRequires: null,
		fallback: null,
		api: 'planned: slide.showEvents',
		packageContract: 'p14:showEvtLst on sld extLst. Opt-in.',
		officeFixture: 'planned test/fixtures/ms-pptx/show-events.roundtrip.pptx',
		schema: '150_…2010-main-schema.md',
	},
	{
		id: 'image-default-dpi',
		title: 'Default image DPI',
		spec: '§2.2.7 / §2.3.1.5',
		issue: 89,
		status: 'supported',
		namespace: MS_PPTX_NAMESPACES.p14,
		prefix: 'p14',
		host: 'p:presentationPr/p:extLst',
		part: 'ppt/presProps.xml',
		contentType: 'application/vnd.openxmlformats-officedocument.presentationml.presProps+xml',
		relationship: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/presProps',
		targetMode: 'Internal',
		wrapper: 'extLst',
		extUri: '{D31A062A-798A-4329-ABDD-BBA856620510}',
		choiceRequires: null,
		fallback: null,
		api: 'pptx.defaultImageDpi',
		packageContract: 'Emit only when > 0. URI + p14:defaultImageDpi@val MUST match.',
		officeFixture: 'test/issues.test.ts #gap4. Office: image compression DPI preference survives save.',
		schema: '150_…2010-main-schema.md',
	},
	{
		id: 'image-discard-edit',
		title: 'Discard image edit data',
		spec: '§2.2.7 / §2.3.1.6',
		issue: 89,
		status: 'supported',
		namespace: MS_PPTX_NAMESPACES.p14,
		prefix: 'p14',
		host: 'p:presentationPr/p:extLst',
		part: 'ppt/presProps.xml',
		contentType: 'application/vnd.openxmlformats-officedocument.presentationml.presProps+xml',
		relationship: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/presProps',
		targetMode: 'Internal',
		wrapper: 'extLst',
		extUri: '{E76CE94A-603C-4142-B9EB-6D1370010A27}',
		choiceRequires: null,
		fallback: null,
		api: 'pptx.discardImageEditData',
		packageContract: 'Emit only when true. p14:discardImageEditData val="1".',
		officeFixture: 'semantic: presProps ext present when set. Office: crop/edit data discarded on save.',
		schema: '150_…2010-main-schema.md',
	},
	{
		id: 'math-omml',
		title: 'Math (OMML) extensions',
		spec: '§2.2.8',
		issue: 77,
		status: 'supported',
		namespace: MS_PPTX_NAMESPACES.a14,
		prefix: 'a14',
		host: 'a:p / run siblings; presentationPr ext for a14:m flag',
		part: 'ppt/slides/slideN.xml',
		contentType: null,
		relationship: null,
		targetMode: null,
		wrapper: 'mc:AlternateContent',
		extUri: '{4599F94E-CEE6-441E-89CC-EB005ECD8F06}',
		choiceRequires: 'a14',
		fallback: 'plain text run (down-level)',
		api: 'addText({ text, omml }) / math runs',
		packageContract: 'PowerPoint requires a14:m around m:oMath. Bare OMML is stripped on open. presentationPr MAY carry the a14:m ext URI.',
		officeFixture: 'Proven via PowerPoint 16 COM (src/xml/text.ts). Semantic: OMML wrapped in a14:m.',
		schema: '[MS-ODRAWXML] + ECMA-376 math',
	},
	{
		id: 'revision-info-part',
		title: 'Revision Information part',
		spec: '§2.1.2 / §2.7.1.1',
		issue: 90,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p1510,
		prefix: 'p1510',
		host: 'presentation (implicit rel)',
		part: 'ppt/revisionInfo.xml (name not prescribed; root revInfo)',
		contentType: 'application/vnd.ms-powerpoint.revisioninfo+xml',
		relationship: 'http://schemas.microsoft.com/office/2015/10/relationships/revisionInfo',
		targetMode: 'Internal',
		wrapper: 'extLst',
		extUri: null,
		choiceRequires: null,
		fallback: null,
		api: 'planned: pptx.revisionInfo (opt-in)',
		packageContract: 'Zero-or-one part. Implicit rel from Presentation. TargetMode MUST be Internal. Root MUST be revInfo. Part MUST NOT have further rels.',
		officeFixture: 'planned test/fixtures/ms-pptx/revision-info.roundtrip.pptx — cardinality + Internal target + no outbound rels.',
		schema: '154_…2015-10-main-schema.md',
	},
	{
		id: 'changes-info-part',
		title: 'Changes Information part',
		spec: '§2.1.4 / §2.12.1.1',
		issue: 90,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.pc,
		prefix: 'pc',
		host: 'presentation (implicit rel)',
		part: 'ppt/changesInfo.xml (name not prescribed; root chgInfo)',
		contentType: 'application/vnd.ms-powerpoint.changesinfo+xml',
		relationship: 'http://schemas.microsoft.com/office/2016/11/relationships/changesInfo',
		targetMode: 'Internal',
		wrapper: 'extLst',
		extUri: null,
		choiceRequires: null,
		fallback: null,
		api: 'planned: pptx.changesInfo (opt-in)',
		packageContract: 'Zero-or-one part. Implicit rel from Presentation. TargetMode MUST be Internal. Root MUST be chgInfo. Part MUST NOT have further rels.',
		officeFixture: 'planned test/fixtures/ms-pptx/changes-info.roundtrip.pptx',
		schema: '152_…2013-main-command-schema.md',
	},
	{
		id: 'change-mod-id',
		title: 'Shape modification id',
		spec: '§2.2.9 / §2.3.1.19',
		issue: 90,
		status: 'partial',
		namespace: MS_PPTX_NAMESPACES.p14,
		prefix: 'p14',
		host: 'p:nvPr/p:extLst',
		part: 'ppt/slides/slideN.xml',
		contentType: null,
		relationship: null,
		targetMode: null,
		wrapper: 'extLst',
		extUri: '{D42A27DB-BD31-4B8C-83A1-F6EECF244321}',
		choiceRequires: null,
		fallback: null,
		api: 'none (incidental hardcoded p14:modId on some tables); planned unique-per-shape API',
		packageContract: 'Each modId MUST be unique on the slide. Current table path emits a constant val — #90 MUST replace that with a real unique id when tracking is on.',
		officeFixture: 'planned uniqueness contract + Office reshape updates modId.',
		schema: '150_…2010-main-schema.md',
	},
	{
		id: 'change-creation-id',
		title: 'Creation id',
		spec: '§2.2.9 / §2.3.1.4',
		issue: 90,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p14,
		prefix: 'p14',
		host: 'p:cSld/p:extLst',
		part: 'ppt/slides/slideN.xml',
		contentType: null,
		relationship: null,
		targetMode: null,
		wrapper: 'extLst',
		extUri: '{BB962C8B-B14F-4D97-AF65-F5344CB8AC3E}',
		choiceRequires: null,
		fallback: null,
		api: 'planned: slide.creationId (opt-in)',
		packageContract: 'p14:creationId on cSld extLst. Opt-in; unset MUST NOT emit.',
		officeFixture: 'planned test/fixtures/ms-pptx/creation-id.roundtrip.pptx',
		schema: '150_…2010-main-schema.md',
	},
	{
		id: 'comments-author-part',
		title: 'Author part (modern)',
		spec: '§2.1.6 / §2.16.1.1',
		issue: 91,
		status: 'supported',
		namespace: MS_PPTX_NAMESPACES.p188,
		prefix: 'p188',
		host: 'presentation (implicit rel)',
		part: 'ppt/authors.xml',
		contentType: 'application/vnd.ms-powerpoint.authors+xml',
		relationship: 'http://schemas.microsoft.com/office/2018/10/relationships/authors',
		targetMode: 'Internal',
		wrapper: 'extLst',
		extUri: null,
		choiceRequires: null,
		fallback: null,
		api: 'pptx.commentAuthors; auto-collected from addComment author names',
		packageContract: 'Zero-or-one Author part. Implicit rel from Presentation. Root MUST be authorLst. TargetMode Internal. Part MUST NOT have further rels.',
		officeFixture: 'test/issues.test.ts #gap5. Office: author names in Comments pane survive save.',
		schema: '163_…2018-8-main-schema.md',
	},
	{
		id: 'comments-comment-part',
		title: 'Comment part (modern threaded)',
		spec: '§2.1.5 / §2.16.1.2',
		issue: 91,
		status: 'supported',
		namespace: MS_PPTX_NAMESPACES.p188,
		prefix: 'p188',
		host: 'slide (explicit rel)',
		part: 'ppt/comments/commentSlideN.xml',
		contentType: 'application/vnd.ms-powerpoint.comments+xml',
		relationship: 'http://schemas.microsoft.com/office/2018/10/relationships/comments',
		targetMode: 'Internal',
		wrapper: 'extLst',
		extUri: null,
		choiceRequires: null,
		fallback: null,
		api: 'slide.addComment({ text, author, x, y, replies })',
		packageContract: 'Explicit rel from Slide only. Root MUST be cmLst. TargetMode Internal. Current impl anchors via pc:sldMkLst + replyLst. Distinct from legacy cmAuthorLst.',
		officeFixture: 'test/issues.test.ts #gap5. Office: thread + reply survive save; slide without comments MUST NOT have a comments rel.',
		schema: '163_…2018-8-main-schema.md',
	},
	{
		id: 'comments-comment-rel',
		title: 'Slide commentRel pointer',
		spec: '§2.2.10',
		issue: 91,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p188,
		prefix: 'p188',
		host: 'p:sld/p:extLst',
		part: 'ppt/slides/slideN.xml',
		contentType: null,
		relationship: 'http://schemas.microsoft.com/office/2018/10/relationships/comments',
		targetMode: 'Internal',
		wrapper: 'extLst',
		extUri: '{6950BFC3-D8DA-4A85-94F7-54DA5524770B}',
		choiceRequires: null,
		fallback: null,
		api: 'planned: emitted automatically with addComment',
		packageContract: 'commentRel on sld extLst MUST point at the slide Comment part. Current impl uses only the slide .rels; #91 SHOULD add this ext for Office parity.',
		officeFixture: 'planned: #gap5 extended — sld extLst commentRel rId matches comments rel.',
		schema: '163_…2018-8-main-schema.md',
	},
	{
		id: 'comments-presence',
		title: 'Legacy comment presenceInfo',
		spec: '§2.2.10',
		issue: 91,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p15,
		prefix: 'p15',
		host: 'p:cmAuthor/p:extLst (legacy comment authors)',
		part: 'ppt/commentAuthors.xml (legacy)',
		contentType: 'application/vnd.openxmlformats-officedocument.presentationml.commentAuthors+xml',
		relationship: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/commentAuthors',
		targetMode: 'Internal',
		wrapper: 'extLst',
		extUri: '{19B8F6BF-5375-455C-9EA6-DF929625EA0E}',
		choiceRequires: null,
		fallback: null,
		api: 'planned only if legacy cmAuthorLst is kept; modern path uses p188 authors',
		packageContract: 'presenceInfo on legacy cmAuthor. Modern p188 authors do not use this ext. Do not mix legacy + modern parts unless Office requires both.',
		officeFixture: 'planned only if legacy comments are implemented.',
		schema: '151_…2012-main-schema.md',
	},
	{
		id: 'comments-threading',
		title: 'Legacy comment threadingInfo',
		spec: '§2.2.10',
		issue: 91,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p15,
		prefix: 'p15',
		host: 'p:cm/p:extLst (legacy comments)',
		part: 'ppt/comments/commentN.xml (legacy)',
		contentType: 'application/vnd.openxmlformats-officedocument.presentationml.comments+xml',
		relationship: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments',
		targetMode: 'Internal',
		wrapper: 'extLst',
		extUri: '{C676402C-5697-4E1C-873F-D02D1690AC5C}',
		choiceRequires: null,
		fallback: null,
		api: 'n/a on modern p188 path (replyLst); planned if legacy comments are emitted',
		packageContract: 'threadingInfo on legacy p:cm. Modern threads use p188:replyLst instead.',
		officeFixture: 'planned only if legacy comments are implemented.',
		schema: '151_…2012-main-schema.md',
	},
	{
		id: 'comments-changes',
		title: 'Comment change records + monikers',
		spec: '§2.18 / §2.19',
		issue: 91,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p2206c,
		prefix: 'p2206c',
		host: 'Changes Information part / comment monikers',
		part: 'ppt/changesInfo.xml (shared with #90) + comment monikers',
		contentType: 'application/vnd.ms-powerpoint.changesinfo+xml',
		relationship: 'http://schemas.microsoft.com/office/2016/11/relationships/changesInfo',
		targetMode: 'Internal',
		wrapper: 'extLst',
		extUri: null,
		choiceRequires: null,
		fallback: null,
		api: 'planned: opt-in comment change log (cmChg + cmMkLst)',
		packageContract: 'cmChg (2022/06/command) references cmMkLst (2019/9/command). Requires the Changes Information part from #90. Opt-in.',
		officeFixture: 'planned test/fixtures/ms-pptx/comment-changes.roundtrip.pptx',
		schema: '167_…2022-06-main-command-schema.md + 164_…2019-9-main-command-schema.md',
	},
	{
		id: 'comments-tasks',
		title: 'Comment / collaboration tasks',
		spec: '§2.20',
		issue: 91,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p2208,
		prefix: 'p2208',
		host: 'comment / task extension host',
		part: '(inline ext on comment or task host)',
		contentType: null,
		relationship: null,
		targetMode: null,
		wrapper: 'extLst',
		extUri: null,
		choiceRequires: null,
		fallback: null,
		api: 'planned: comment.task / pptx.tasks (opt-in)',
		packageContract: 'taskDetails in 2022/08/main. Opt-in collaboration metadata; do not emit empty task lists.',
		officeFixture: 'planned test/fixtures/ms-pptx/tasks.roundtrip.pptx',
		schema: '168_…2022-08-main-schema.md',
	},
	{
		id: 'comments-reactions',
		title: 'Reactions',
		spec: '§2.21',
		issue: 91,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p2203,
		prefix: 'p2203',
		host: 'parent element extLst (comment / object)',
		part: '(inline ext)',
		contentType: null,
		relationship: null,
		targetMode: null,
		wrapper: 'extLst',
		extUri: null,
		choiceRequires: null,
		fallback: null,
		api: 'planned: comment.reactions (opt-in)',
		packageContract: 'reactions in 2022/03/main. Opt-in; empty list MUST NOT be emitted.',
		officeFixture: 'planned test/fixtures/ms-pptx/reactions.roundtrip.pptx',
		schema: '166_…2022-03-main-schema.md',
	},
	{
		id: 'guides-slide',
		title: 'Slide / view guides',
		spec: '§2.2.11 / §2.4.1.6',
		issue: 88,
		status: 'partial',
		namespace: MS_PPTX_NAMESPACES.p15,
		prefix: 'p15',
		host: 'p:presentation/p:extLst (also layout/master/handout/notes — other URIs)',
		part: 'ppt/presentation.xml',
		contentType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml',
		relationship: null,
		targetMode: null,
		wrapper: 'extLst',
		extUri: '{EFAFB233-063F-42B5-8137-9DF3F51BA10A}',
		choiceRequires: null,
		fallback: null,
		api: 'pptx.guides = [{ orient, pos, color, name, userDrawn }]',
		packageContract: 'Presentation URI {EFAFB233-…}. pos is EMU; p15:clr child is required. Other hosts use distinct URIs (layout {DCECCB84-…}, master {27BBF7A9-…}, handout {56416CCD-…}, notes {620B2872-…}) — not yet emitted. #88 SHOULD add those hosts if API grows.',
		officeFixture: 'test/issues.test.ts #gap3. Office: ruler guides visible after open/save.',
		schema: '151_…2012-main-schema.md',
	},
	{
		id: 'guides-notes',
		title: 'Notes guides',
		spec: '§2.2.11 / §2.4.1.3',
		issue: 88,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p15,
		prefix: 'p15',
		host: 'p:presentation/p:extLst',
		part: 'ppt/presentation.xml',
		contentType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml',
		relationship: null,
		targetMode: null,
		wrapper: 'extLst',
		extUri: '{2D200454-40CA-4A62-9FC3-DE9A4176ACB9}',
		choiceRequires: null,
		fallback: null,
		api: 'planned: pptx.notesGuides',
		packageContract: 'p15:notesGuideLst under presentation extLst. Same CT_GuideList rules as sldGuideLst.',
		officeFixture: 'planned test/fixtures/ms-pptx/notes-guides.roundtrip.pptx',
		schema: '151_…2012-main-schema.md',
	},
	{
		id: 'chart-tracking',
		title: 'Chart tracking reference based',
		spec: '§2.2.12 / §2.4.1.1',
		issue: 93,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p15,
		prefix: 'p15',
		host: 'p:presentationPr/p:extLst',
		part: 'ppt/presProps.xml',
		contentType: 'application/vnd.openxmlformats-officedocument.presentationml.presProps+xml',
		relationship: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/presProps',
		targetMode: 'Internal',
		wrapper: 'extLst',
		extUri: '{FD5EFAAD-0ECE-453E-9831-46B23BE46B34}',
		choiceRequires: null,
		fallback: null,
		api: 'planned: pptx.chartTrackingRefBased',
		packageContract: 'Opt-in. Unset MUST NOT change chart XML. When set, emit exactly this URI + p15:chartTrackingRefBased.',
		officeFixture: 'planned test/fixtures/ms-pptx/chart-tracking.roundtrip.pptx — charts still render; flag survives save.',
		schema: '151_…2012-main-schema.md',
	},
	{
		id: 'office-app',
		title: 'Office App / web extension ref',
		spec: '§2.2.13',
		issue: 87,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.we,
		prefix: 'we + p13app',
		host: 'p:spTree / p:grpSp',
		part: 'ppt/slides/slideN.xml + web extension part ([MS-OWEXML])',
		contentType: 'application/vnd.ms-office.webextension+xml',
		relationship: '[MS-OWEXML] webextensionref / webextension',
		targetMode: 'Internal',
		wrapper: 'mc:AlternateContent',
		extUri: null,
		choiceRequires: 'we',
		fallback: 'p:pic',
		api: 'planned: slide.addOfficeApp / addWebExtension',
		packageContract: 'Choice namespaces: webextension/2010/11 + powerpoint/2013/contentapp. Fallback MUST be p:pic. Validate webextension part rels per [MS-OWEXML] §2.1.3.',
		officeFixture: 'planned test/fixtures/ms-pptx/office-app.roundtrip.pptx — app chrome + pic fallback.',
		schema: '[MS-OWEXML] 11.0',
	},
	{
		id: 'zoom-slide',
		title: 'Slide zoom',
		spec: '§2.2.15 / §2.10',
		issue: 88,
		status: 'supported',
		namespace: MS_PPTX_NAMESPACES.p16slz,
		prefix: 'p16',
		host: 'p:spTree / p:grpSp',
		part: 'ppt/slides/slideN.xml',
		contentType: null,
		relationship: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/image (cover) + slide target',
		targetMode: 'Internal',
		wrapper: 'mc:AlternateContent',
		extUri: null,
		choiceRequires: 'p16',
		fallback: 'p:pic',
		api: 'slide.addZoom({ slideNum, cover, … })',
		packageContract: 'Choice p16:sldZm / sldZmObj@sldId. Optional p166:zmPr. Cover image rel required. Fallback MUST be p:pic.',
		officeFixture: 'test/issues.test.ts addZoom. Office: click zoom navigates; down-level shows picture.',
		schema: '158_…2016-slidezoom-schema.md + 156_…2016-6-main-schema.md',
	},
	{
		id: 'zoom-section',
		title: 'Section zoom',
		spec: '§2.2.15 / §2.9',
		issue: 88,
		status: 'supported',
		namespace: MS_PPTX_NAMESPACES.p16sz,
		prefix: 'p16',
		host: 'p:spTree / p:grpSp',
		part: 'ppt/slides/slideN.xml',
		contentType: null,
		relationship: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/image (cover)',
		targetMode: 'Internal',
		wrapper: 'mc:AlternateContent',
		extUri: null,
		choiceRequires: 'p16',
		fallback: 'p:pic',
		api: 'slide.addSectionZoom({ sectionTitle, cover, … })',
		packageContract: 'Choice p16:sectionZm / sectionZmObj@sectionId MUST equal the sectionLst GUID. Fallback MUST be p:pic.',
		officeFixture: 'test/issues.test.ts section GUID match. Office: section zoom navigates to section.',
		schema: '157_…2016-sectionzoom-schema.md',
	},
	{
		id: 'zoom-summary',
		title: 'Summary zoom',
		spec: '§2.2.15 / §2.11',
		issue: 88,
		status: 'supported',
		namespace: MS_PPTX_NAMESPACES.p16smz,
		prefix: 'p16',
		host: 'p:spTree / p:grpSp',
		part: 'ppt/slides/slideN.xml',
		contentType: null,
		relationship: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/image (cover)',
		targetMode: 'Internal',
		wrapper: 'mc:AlternateContent',
		extUri: null,
		choiceRequires: 'p16',
		fallback: 'p:grpSp',
		api: 'slide.addSummaryZoom({ sectionTitle, cover, … })',
		packageContract: 'Choice p16:summaryZm + required gridLayout|fixedLayout. Fallback MUST be p:grpSp (not pic). sectionId GUID MUST match sectionLst.',
		officeFixture: 'semantic summary-zoom tests. Office: summary zoom + layout choice survive save.',
		schema: '159_…2016-summaryzoom-schema.md',
	},
	{
		id: 'view-readonly',
		title: 'Read-only recommended',
		spec: '§2.2.16 / §2.14.1.1',
		issue: 89,
		status: 'supported',
		namespace: MS_PPTX_NAMESPACES.p1710,
		prefix: 'p1710',
		host: 'p:presentationPr/p:extLst',
		part: 'ppt/presProps.xml',
		contentType: 'application/vnd.openxmlformats-officedocument.presentationml.presProps+xml',
		relationship: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/presProps',
		targetMode: 'Internal',
		wrapper: 'extLst',
		extUri: '{1BD7E111-0CB8-44D6-8891-C1BB2F81B7CC}',
		choiceRequires: null,
		fallback: null,
		api: 'pptx.readonlyRecommended',
		packageContract: 'Emit only when true. p1710:readonlyRecommended val="1".',
		officeFixture: 'test/issues.test.ts #gap4. Office: "recommended read-only" prompt on open.',
		schema: '160_…2017-10-main-schema.md',
	},
	{
		id: 'design-elem',
		title: 'Design element flag',
		spec: '§2.2.17 / §2.5.1.1',
		issue: 92,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p15m,
		prefix: 'p15m',
		host: 'p:nvPr/p:extLst',
		part: 'ppt/slides/slideN.xml',
		contentType: null,
		relationship: null,
		targetMode: null,
		wrapper: 'extLst',
		extUri: '{386F3935-93C4-4BCD-93E2-E3B085C9AB24}',
		choiceRequires: null,
		fallback: null,
		api: 'planned: shape/slide designElement (opt-in)',
		packageContract: 'p15:designElem (2015/main) on nvPr. Designer metadata; opt-in.',
		officeFixture: 'planned test/fixtures/ms-pptx/design-elem.roundtrip.pptx',
		schema: '155_…2015-main-schema.md',
	},
	{
		id: 'classification',
		title: 'Classification outcome',
		spec: '§2.2.18 / §2.15.1.1',
		issue: 92,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p184,
		prefix: 'p184',
		host: 'p:nvPr/p:extLst',
		part: 'ppt/slides/slideN.xml',
		contentType: null,
		relationship: null,
		targetMode: null,
		wrapper: 'extLst',
		extUri: '{1162E1C5-73C7-4A58-AE30-91384D911F3F}',
		choiceRequires: null,
		fallback: null,
		api: 'planned: opt-in classification metadata (MUST stay opt-in)',
		packageContract: 'Compliance metadata. MUST NOT be default-on. Validate extLst URI + 2018/4/main classification child.',
		officeFixture: 'planned test/fixtures/ms-pptx/classification.roundtrip.pptx — flag absent unless API set.',
		schema: '162_…2018-4-main-schema.md',
	},
	{
		id: 'designer-props',
		title: 'Designer properties',
		spec: '§2.2.19 / §2.17.1.1',
		issue: 92,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p2020,
		prefix: 'p2020',
		host: 'p:nvPr/p:extLst',
		part: 'ppt/slides/slideN.xml',
		contentType: null,
		relationship: null,
		targetMode: null,
		wrapper: 'extLst',
		extUri: '{E7BDC344-281C-4309-B0C6-D0EE65EED2A8}',
		choiceRequires: null,
		fallback: null,
		api: 'planned: shape.designerProps (opt-in)',
		packageContract: 'designPr in 2020/02/main on nvPr. Server-driven Designer metadata; opt-in.',
		officeFixture: 'planned test/fixtures/ms-pptx/design-pr.roundtrip.pptx',
		schema: '165_…2020-02-main-schema.md',
	},
	{
		id: 'designer-tags',
		title: 'Designer tags',
		spec: '§2.2.20 / §2.17.1.2',
		issue: 92,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p2020,
		prefix: 'p2020',
		host: 'p:sldId/p:extLst',
		part: 'ppt/presentation.xml',
		contentType: null,
		relationship: null,
		targetMode: null,
		wrapper: 'extLst',
		extUri: '{E3EDB536-0D56-4F60-86BA-61A60CA02DAB}',
		choiceRequires: null,
		fallback: null,
		api: 'planned: slide.designerTags (opt-in)',
		packageContract: 'designTagLst on sldId extLst (presentation sldIdLst), not nvPr. Opt-in.',
		officeFixture: 'planned test/fixtures/ms-pptx/design-tags.roundtrip.pptx',
		schema: '165_…2020-02-main-schema.md',
	},
	{
		id: 'placeholder-type-ext',
		title: 'Modern placeholder type extension',
		spec: '§2.22.1.1',
		issue: 92,
		status: 'planned',
		namespace: MS_PPTX_NAMESPACES.p2302,
		prefix: 'p2302',
		host: 'p:ph / placeholder extLst',
		part: 'ppt/slideLayouts/slideLayoutN.xml (typical)',
		contentType: 'application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml',
		relationship: null,
		targetMode: null,
		wrapper: 'extLst',
		extUri: null,
		choiceRequires: null,
		fallback: null,
		api: 'planned: placeholder type extension (opt-in)',
		packageContract: 'phTypeExt in 2023/02/main. Validate extLst integration on p:ph. Unset MUST keep ECMA-376 ph@type only.',
		officeFixture: 'planned test/fixtures/ms-pptx/ph-type-ext.roundtrip.pptx',
		schema: '169_…2023-02-main-schema.md',
	},
]

export const MS_PPTX_EXTENSIONS: readonly MsPptxExtension[] = EXT

export const MS_PPTX_CHILD_ISSUES = [87, 88, 89, 90, 91, 92, 93] as const

export function getExtension (id: string): MsPptxExtension | undefined {
	return EXT.find(e => e.id === id)
}

export function extensionsForIssue (issue: number): MsPptxExtension[] {
	return EXT.filter(e => e.issue === issue)
}

export function extensionsByStatus (status: ExtensionStatus): MsPptxExtension[] {
	return EXT.filter(e => e.status === status)
}
